version: '2'

services:

  web:
    image: cs61a/ok-server
    build: ..
    restart: always
    command: /bin/bash -c "./manage.py resetdb && ./manage.py server"
    ports:
      - "80:5000"
    volumes:
      - ..:/code
    links:
      - db
      - redis

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: 'okdev'
      MYSQL_PASSWORD: 'okdev'
      MYSQL_DATABASE: 'okdev'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    tmpfs:
      - /var/lib/mysql

  redis:
    image: redis:alpine
    restart: always
