web:
  image: cs61a/ok-server
  restart: 'no'
  command: py.test --cov-report term-missing --cov=server tests/
  environment:
    OK_ENV: 'test'
    DATABASE_URL: 'mysql://okdev:okdev@db:3306/okdev?charset=utf8mb4'
    REDIS_HOST: 'redis'
  links:
    - db
    - redis
